### ISSUE TITLE
Thanks, small suggestion on function implementation

### ISSUE THREAD

**Issue by tlambert03** [rec/dtyper#1]
Thanks for writing this up, and linking it over in the typer repo!  good stuff :)

small suggestion on the `function` implementation.  the `inspect.Signature` object has some conveniences that provide all of the parameter binding and validation that you're doing here.  The following implementation 
- uses `Signature.bind` and `apply_defaults` to the same effect.
- sets `__signature__` so inspection of the returned object returns the proper value.  
- works when the default parameter _isn't_ a typer.Option that has a `default` attribute
-  keeps all typing info of the original function using `ParamSpec`

```python
from typing_extensions import ParamSpec
from typing import TypeVar, Callable
from functools import wraps
from inspect import signature

P = ParamSpec("P")
R = TypeVar("R")


def function(typer_command: Callable[P, R]) -> Callable[P, R]:

    sig = signature(typer_command)
    fixed_defaults = [
        p.replace(default=getattr(p.default, "default", p.default))
        for p in sig.parameters.values()
    ]
    new_sig = sig.replace(parameters=fixed_defaults)

    @wraps(typer_command)
    def wrapped(*args: P.args, **kwargs: P.kwargs) -> R:
        bound = new_sig.bind(*args, **kwargs)
        bound.apply_defaults()
        return typer_command(*bound.args, **bound.kwargs)

    wrapped.__signature__ = new_sig  # type: ignore
    return wrapped
```

feel free to use some/any of that if you like.  thanks again

**Comment by rec** [comment]
Hello, Tally!

This is fascinating material, and I'm sorta shocked I didn't know about `inspect.Signature`.

In my defense, the code I actually use in my projects is the one that makes a `dataclass` out of a typer command, and I just threw in the `function` one at the end when I looked at the conversation about the issue and realized that this is what people wanted...

I can't do this today, likely tomorrow, else Monday.  I also accept pull requests... 

Thanks again!!!

**Comment by tlambert03** [comment]
> In my defense

No defense necessary!   Sorry for the somewhat obnoxious unsolicited advice 😂

**Comment by rec** [comment]
Pff, I'm pathetically grateful for the interest.  :-D

Sure you don't wanna submit a pull request?  Add to your laurels, make this repo seem more important?

**Comment by tlambert03** [comment]
No, I’ll do the pull request later today!  Sorry, should have just done it to begin with :)
