### ISSUE TITLE
Provide example on how to use `dtyper.Typer`

### ISSUE THREAD

**Issue by lainisourgod** [rec/dtyper#6]
Hi! I'm curious of how to use `dtyper.Typer` and when. Can it be used as "don`t put @dtyper.function on every command, just do app = dtyper.Typer and everything is set`?

**Comment by rec** [comment]
That is exactly right!

I'll make a tweak to emphasize this in the docs sometime tomorrow, see if you like it, and close the issue.

**Comment by rec** [comment]
Check it out.

https://github.com/rec/dtyper/blob/main/README.md
